//! Static, embedded English dictionary with O(log n) word lookup.
//!
//! The sorted word list and its parallel definitions are compiled into the
//! binary as two raw text blobs. A build script precomputes a compact
//! `(offset, length)` index into each blob (see build.rs), so a lookup is a
//! binary search touching only a handful of cache lines. Crucially there is no
//! per-invocation parsing or allocation of the 12 MB definition data: the blobs
//! live in the read-only data segment and cost nothing to "load".

use std::cmp::Ordering;
use std::convert::TryInto;

/// Newline-delimited blobs baked into the executable.
const WORDS: &str = include_str!("../words.txt");
const DEFNS: &str = include_str!("../defns.txt");

/// `(start: u32, len: u32)` little-endian records, one per line of the matching
/// blob, generated by build.rs. Entry `i` of `WORD_IDX` and of `DEFN_IDX`
/// describe the same dictionary entry.
const WORD_IDX: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/words.idx"));
const DEFN_IDX: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/defns.idx"));

const RECORD: usize = 8; // bytes per (u32, u32) index record

/// Returns the `&str` slice of `blob` described by record `i` of `idx`.
fn slice_at(blob: &'static str, idx: &[u8], i: usize) -> &'static str {
    let p = i * RECORD;
    let start = u32::from_le_bytes(idx[p..p + 4].try_into().unwrap()) as usize;
    let len = u32::from_le_bytes(idx[p + 4..p + 8].try_into().unwrap()) as usize;
    &blob[start..start + len]
}

/// Looks up `word` and returns its raw definition line: a JSON array of
/// "pos\tdefn\texample" strings. Returns `None` if the word is absent. The word
/// list is sorted, so this is a binary search.
pub fn lookup(word: &str) -> Option<&'static str> {
    let mut lo = 0;
    let mut hi = WORD_IDX.len() / RECORD;
    while lo < hi {
        let mid = lo + (hi - lo) / 2;
        match slice_at(WORDS, WORD_IDX, mid).cmp(word) {
            Ordering::Less => lo = mid + 1,
            Ordering::Greater => hi = mid,
            Ordering::Equal => return Some(slice_at(DEFNS, DEFN_IDX, mid)),
        }
    }
    None
}
